version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hotel-postgres-db
    environment:
      POSTGRES_DB: hotel-booking-db
      POSTGRES_USER: hotel-booking
      POSTGRES_PASSWORD: hotel-booking@2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes persistentes
volumes:
  postgres_data:
    driver: local

# Rede personalizada
networks:
  app-network:
    driver: bridge
